# @format

# docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data:
